Identifiers typographically unambiguous
Bareflank/llvm-project pull request #5
Opened 2020-06-22 22:48 UTC by ytuo

2020-06-22 23:06 UTC, ytuo commented
@rianquinn @connojd 
not sure if this is the best way to do string manipulation (algorithmically/in c++)

2020-06-23 18:40 UTC, rianquinn requested changes

2020-06-23 18:40 UTC, rianquinn commented on clang-tools-extra/clang-tidy/bsl/IdentifierTypographicallyUnambiguousCheck.cpp
> +          name.replace(i, 1, "o");
I like this approach

2020-06-23 18:40 UTC, rianquinn commented on clang-tools-extra/test/clang-tidy/checkers/bsl-identifier-typographically-unambiguous.cpp
> +int id1_a_b_c;
Does this test actually detect things that are not-compliant? This doesn't seem like this test is complete. I think there should be some LLVM specific comments that detect the non-compliant cases to prove that this code is working.

2020-07-31 16:18 UTC, merged