Copy/move constructor and assignment operator access specifier
Bareflank/llvm-project pull request #6
Opened 2020-06-24 00:04 UTC by ytuo

A12-8-6

2020-07-31 16:23 UTC, rianquinn requested changes

2020-07-31 16:23 UTC, rianquinn commented on clang-tools-extra/test/clang-tidy/checkers/bsl-copy-move-access-specifier.cpp
> +  virtual ~A() = 0;
In all cases, you are using a virtual destructor. You need to add some tests for non-virtual destructors (both public and protected)

2020-07-31 16:23 UTC, rianquinn commented on clang-tools-extra/test/clang-tidy/checkers/bsl-copy-move-access-specifier.cpp
> +  virtual ~A() = 0;
Also need these for both the failure case and the good case

2020-08-07 16:43 UTC, cjams requested changes

2020-08-07 16:43 UTC, connojd commented on clang-tools-extra/clang-tidy/bsl/CopyMoveAccessSpecifierCheck.cpp
> +    if (Mgr->getFileID(LocV) != Mgr->getMainFileID())
Remove getMainFileID check

2020-08-10 17:51 UTC, closed without merging