Struct definition
Bareflank/llvm-project pull request #7
Opened 2020-06-24 17:22 UTC by ytuo

A11-0-2

Commented out code is the "stricter" version that enforces structs be pod-like/C-like.

2020-07-31 16:26 UTC, rianquinn requested changes

2020-07-31 16:26 UTC, rianquinn commented on clang-tools-extra/test/clang-tidy/checkers/bsl-struct-def.cpp
> +  S2(){};
Need test cases for when a constructor has args

2020-07-31 16:26 UTC, rianquinn commented on clang-tools-extra/test/clang-tidy/checkers/bsl-struct-def.cpp
> +  ~S4();
what about virtual destructors and virtual members? Neither are allowed.

2020-08-03 19:34 UTC, ytuo commented
allows explicitly deleted and defaulted constructors

2020-08-07 16:20 UTC, cjams requested changes

2020-08-07 16:20 UTC, connojd commented on clang-tools-extra/clang-tidy/bsl/StructDefCheck.cpp
> +    if (Mgr->getFileID(StructLoc) != Mgr->getMainFileID())
remove all getMainFileID checks

2020-08-07 16:20 UTC, connojd commented on clang-tools-extra/clang-tidy/bsl/StructDefCheck.cpp
> +  auto StructDef = Result.Nodes.getNodeAs<CXXMethodDecl>("special");
This and the "virtual" matcher will match any method decl, even if they aren't defined in a struct. You could add a `hasParent(isStruct())` to these two matchers that checks that the recorddecl parent is a struct

2020-08-14 17:03 UTC, rianquinn commented
ready

2020-08-14 18:30 UTC, merged